# 1 张量

## 1.1 张量是什么

张量是一个具有n个维度的数表。在PyTorch中，张量可以直接被如下定义：

In [ ]:
import torch
from rich import print

In [1]:
A = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("张量A如下所示：")
print(A)

/usr/local/lib/python3.8/dist-packages/tqdm-4.65.0-py3.8.egg/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


张量A如下所示：

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

通过如上的方式，我们就在PyTorch中定义了一个2行4列的矩阵（2维张量）。

在PyTorch中，张量具备一些重要的属性：

（1）形状

形状（或维度）是张量的一个重要属性。张量的形状隐含着张量的大小以及可以如何处理张量等重要信息。可以使用`shape`属性来查看张量的形状与维度。

In [2]:
print("张量A的形状为：")
print(A.shape)

print("张量A的维度为：")
print(len(A.shape))

张量A的形状为：

torch.Size([2, 4])

张量A的维度为：

2

（2）数据类型

张量的数据类型决定我们可以用什么样的方式去处理张量。可以使用`dtype`属性来查看张量的数据类型。

In [3]:
print("张量A的数据类型为：")
print(A.dtype)

张量A的数据类型为：

torch.float32

（3）计算设备

张量的计算设备决定了使用什么样的设备去计算张量。可以使用`device`属性来查看张量所在的计算设备。

In [4]:
print("张量A的计算设备为：")
print(A.device)

张量A的计算设备为：

cpu

可以使用`to`方法来改变张量的数据类型与计算设备。

In [5]:
A2 = A.to(torch.int32)

print("张量A2的数据类型为：")
print(A2.dtype)

# 如果你有CUDA，再执行下面的代码，否则注释之
A3 = A.to(torch.device("cuda"))

print("张量A3的计算设备为：")
print(A3.device)

A2的数据类型为：

torch.int32

A3的计算设备为：

cuda:0

## 1.2 张量的操作

### 四则运算

张量的四则运算可以直接使用运算符进行。在进行四则运算的时候，一定需要时刻关注张量的形状。

In [6]:
B1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 形状为[3, 4]

B2 = torch.tensor([
    [1, 4, 7, 10],
    [2, 5, 8, 11],
    [3, 6, 9, 12]
]) # 形状为[3, 4]

B3 = torch.tensor([
    3, 5, 7
]) # 形状为[3]

B4 = torch.tensor([
    2, 4, 6, 8
]) # 形状为[4]

# B1与B2, 形状相同，可以直接相加、相减与逐元素相乘、相除

C1 = B1 + B2
C2 = B1 - B2
C3 = B1 * B2
C4 = B1 / B2

print("张量C1如下所示：")
print(C1)
print("张量C2如下所示：")
print(C2)
print("张量C3如下所示：")
print(C3)
print("张量C4如下所示：")
print(C4)

# B1与B4，由于B4的长度与B1最后一维的长度相同，可以进行逐元素（相当于逐列）相加、相减、相乘、相除

D1 = B1 + B4
D2 = B1 - B4
D3 = B1 * B4
D4 = B1 / B4

print("张量D1如下所示：")
print(D1)
print("张量D2如下所示：")
print(D2)
print("张量D3如下所示：")
print(D3)
print("张量D4如下所示：")
print(D4)

# B1与B3，由于B3的长度并不与B1最后一维长度相同，所以必须将B1转置（使得B1.T最后一维长度与B3相同）后才能进行逐元素运算，运算结果再次转置可以看作逐行

E1 = (B1.T + B3).T
E2 = (B1.T - B3).T
E3 = (B1.T * B3).T
E4 = (B1.T / B3).T

print("张量E1如下所示：")
print(E1)
print("张量E2如下所示：")
print(E2)
print("张量E3如下所示：")
print(E3)
print("张量E4如下所示：")
print(E4)

# 矩阵的相乘可以通过@符号进行

F = B1.T @ B2

print("张量F如下所示：")
print(F)

张量C1如下所示：

tensor([[ 2,  6, 10, 14],
        [ 7, 11, 15, 19],
        [12, 16, 20, 24]])

张量C2如下所示：

tensor([[ 0, -2, -4, -6],
        [ 3,  1, -1, -3],
        [ 6,  4,  2,  0]])

张量C3如下所示：

tensor([[  1,   8,  21,  40],
        [ 10,  30,  56,  88],
        [ 27,  60,  99, 144]])

张量C4如下所示：

tensor([[1.0000, 0.5000, 0.4286, 0.4000],
        [2.5000, 1.2000, 0.8750, 0.7273],
        [3.0000, 1.6667, 1.2222, 1.0000]])

张量D1如下所示：

tensor([[ 3,  6,  9, 12],
        [ 7, 10, 13, 16],
        [11, 14, 17, 20]])

张量D2如下所示：

tensor([[-1, -2, -3, -4],
        [ 3,  2,  1,  0],
        [ 7,  6,  5,  4]])

张量D3如下所示：

tensor([[ 2,  8, 18, 32],
        [10, 24, 42, 64],
        [18, 40, 66, 96]])

张量D4如下所示：

tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [2.5000, 1.5000, 1.1667, 1.0000],
        [4.5000, 2.5000, 1.8333, 1.5000]])

张量E1如下所示：

tensor([[ 4,  5,  6,  7],
        [10, 11, 12, 13],
        [16, 17, 18, 19]])

张量E2如下所示：

tensor([[-2, -1,  0,  1],
        [ 0,  1,  2,  3],
        [ 2,  3,  4,  5]])

张量E3如下所示：

tensor([[ 3,  6,  9, 12],
        [25, 30, 35, 40],
        [63, 70, 77, 84]])

张量E4如下所示：

tensor([[0.3333, 0.6667, 1.0000, 1.3333],
        [1.0000, 1.2000, 1.4000, 1.6000],
        [1.2857, 1.4286, 1.5714, 1.7143]])

张量F如下所示：

tensor([[ 38,  83, 128, 173],
        [ 44,  98, 152, 206],
        [ 50, 113, 176, 239],
        [ 56, 128, 200, 272]])

### 倒维

在多维张量中，可以使用`.permute()`方法来倒转张量的维度（例如把第3个维度提前至第1个维度）。

In [7]:
G1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 形状为[3, 4]

print("张量G1的形状为：")
print(G1.shape)

G2 = G1.permute(1, 0) # 原本的维度索引是[0, 1]，现在的维度索引是[1, 0]
# 以上代码等价于G2 = G1.T

print("张量G2的形状为：")
print(G2.shape)

张量G1的形状为：

torch.Size([3, 4])

张量G2的形状为：

torch.Size([4, 3])

### 变形

运用`.reshape()`操作改变张量的形状。例如，可以把张量展开成1个维度。

运用`.view()`方法也可以改变张量的形状，具体参数与`.reshape()`类似。

In [ ]:
G1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 形状为[3, 4]

print("张量G1的形状为：")
print(G1.shape)

G3 = G1.reshape(12) # 将其展开为长为12的一维向量
# 以上代码等价于G2 = G1.T

print("张量G3的形状为：")
print(G3.shape)

### 拼接

使用`torch.cat()`，可以拼接多个张量，需要保证这些张量在待拼接的维度长度一致；

使用`torch.stack()`，可以将多个n维相同形状的张量拼接成一个n+1维的新张量。

In [8]:
G1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 形状为[3, 4]

G4 = torch.tensor([
    [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24]
]) # 形状为[3, 4]

H1 = torch.cat([G1, G4], dim = 0)

print("张量H1的形状为：")
print(H1.shape)

H2 = torch.cat([G1, G4], dim = 1)

print("张量H2的形状为：")
print(H2.shape)

H3 = torch.stack([G1, G4])

print("张量H3的形状为：")
print(H3.shape)

张量H1的形状为：

torch.Size([6, 4])

张量H2的形状为：

torch.Size([3, 8])

张量H3的形状为：

torch.Size([2, 3, 4])

### 拆分

使用`[]`从原张量中拆分出想要的子张量。

使用单个数作为索引，会在该维上降一个维度；

使用一组数（一个列表）或一个范围，会在该维上取对应索引的数，并将其拼接。

In [9]:
G1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 形状为[3, 4]

I1 = G1[1]

print("张量I1如下所示：")
print(I1)
print("张量I1的形状为：")
print(I1.shape)

I2 = G1[:,1]

print("张量I2如下所示：")
print(I2)
print("张量I2的形状为：")
print(I2.shape)

I3 = G1[1:, :1]

print("张量I3如下所示：")
print(I3)
print("张量I3的形状为：")
print(I3.shape)

张量I1如下所示：

tensor([5, 6, 7, 8])

张量I1的形状为：

torch.Size([4])

张量I2如下所示：

tensor([ 2,  6, 10])

张量I2的形状为：

torch.Size([3])

张量I3如下所示：

tensor([[5],
        [9]])

张量I3的形状为：

torch.Size([2, 1])