# 2 模块

## 2.1 模块是什么

模块是PyTorch中用于组成神经网络的各个组件。在模块的`__init__`函数中，定义了各种参数；在模块的`forward`函数中，则定义了张量在该模块中的处理方法。

In [1]:
import torch
import torch.nn as nn
from rich import print

In [3]:
class LinearAdd(nn.Module):
    def __init__(self, a: float, b: float) -> None:
        super().__init__()
        self.a = a
        self.b = b
    

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        return self.a * x + self.b * y

如上所示，我们定义好了一个叫做`LinearAdd`的模块。它通过继承`nn.Module`类获取其所有特性。在`__init__`函数中，我们将两个固定的参数`a`和`b`传入至模块中，保存为它们的属性；随后，我们在`forward`函数中定义了对两个向量的处理方法：将它们加权求和后返回。

当定义好这个模块之后，我们首先应当对模块实例化，以调用这个模块：

In [4]:
linear_add = LinearAdd(0.6, 0.4) # 调用__init__函数新建实例

x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 6, 7])

随后，我们就可以通过调用实例来执行前向传播，获取结果：

In [5]:
z = linear_add(x, y) # 调用forward函数前向传播

print("张量z如下所示：")
print(z)

张量z如下所示：

tensor([2.6000, 3.6000, 4.6000])

可以看到，经过这个模块得到的张量与我们所期望的一致。

## 2.2 常见的PyTorch预定义模块

### 全连接操作

在PyTorch中，负责全连接操作的模块为`torch.nn.Linear`。它接收2个参数：输入长度`in_features`和输出长度`out_features`，同时还有其它自定义参数。

In [7]:
demo_model = nn.Linear(24, 10) # 全连接层，形状变化设定为24->10

demo_input = torch.rand(16, 24) # 16为批大小，24为输入长度，与全连接层所对应

print("示例输入为：")
print(demo_input)
print("示例输入的形状为：")
print(demo_input.shape)

demo_output = demo_model(demo_input) # 经过全连接层后，形状会为[16, 10]

print("示例输出为：")
print(demo_output)
print("示例输出的形状为：")
print(demo_output.shape)

示例输入为：

tensor([[0.7623, 0.4492, 0.6383, 0.7342, 0.5156, 0.8452, 0.2779, 0.8197, 0.8732,
         0.1768, 0.1166, 0.8044, 0.3285, 0.3672, 0.1206, 0.4046, 0.6493, 0.8440,
         0.5121, 0.6580, 0.7513, 0.5860, 0.0327, 0.0416],
        [0.8952, 0.2976, 0.0293, 0.7941, 0.9135, 0.3753, 0.4836, 0.3909, 0.4705,
         0.2980, 0.3726, 0.8630, 0.4943, 0.6210, 0.0974, 0.1686, 0.4687, 0.6299,
         0.9537, 0.9456, 0.4413, 0.3724, 0.6058, 0.6643],
        [0.0125, 0.6320, 0.9324, 0.8480, 0.3232, 0.8431, 0.4861, 0.5927, 0.1391,
         0.0474, 0.8812, 0.1125, 0.2496, 0.8658, 0.4809, 0.0229, 0.4724, 0.4830,
         0.8300, 0.9488, 0.3790, 0.3031, 0.3192, 0.9411],
        [0.7039, 0.0142, 0.6442, 0.0775, 0.9681, 0.1995, 0.2131, 0.2489, 0.8698,
         0.7058, 0.8775, 0.7328, 0.2645, 0.4994, 0.1355, 0.2537, 0.4815, 0.5744,
         0.8962, 0.7026, 0.2919, 0.9637, 0.7873, 0.9279],
        [0.9138, 0.2198, 0.8207, 0.9461, 0.0985, 0.0373, 0.5371, 0.5614, 0.7007,
         0.3083, 0.9098, 0.5054, 0.2125, 0.0278, 0.4063, 0.9883, 0.4950, 0.2429,
         0.8464, 0.1389, 0.0064, 0.8452, 0.4633, 0.2089],
        [0.1787, 0.1477, 0.4276, 0.4765, 0.2530, 0.1638, 0.4004, 0.3261, 0.2936,
         0.6757, 0.6817, 0.5914, 0.3955, 0.2959, 0.4667, 0.4676, 0.7198, 0.8051,
         0.7775, 0.7573, 0.0690, 0.5316, 0.5430, 0.4055],
        [0.8510, 0.3216, 0.0661, 0.0603, 0.6310, 0.3951, 0.0798, 0.8865, 0.5700,
         0.0838, 0.4649, 0.6971, 0.1880, 0.3011, 0.0285, 0.4931, 0.3267, 0.7722,
         0.3185, 0.2419, 0.9308, 0.2136, 0.6691, 0.6990],
        [0.4081, 0.7668, 0.7787, 0.3402, 0.6896, 0.1693, 0.0587, 0.0941, 0.4014,
         0.5561, 0.9554, 0.6771, 0.4805, 0.4459, 0.6923, 0.9468, 0.9655, 0.5821,
         0.8108, 0.3350, 0.1399, 0.2873, 0.2047, 0.9658],
        [0.2366, 0.1195, 0.8375, 0.7679, 0.5440, 0.1276, 0.4840, 0.0473, 0.9416,
         0.9766, 0.7451, 0.3044, 0.6816, 0.1015, 0.9842, 0.7974, 0.0839, 0.2002,
         0.4660, 0.5835, 0.3173, 0.8702, 0.5265, 0.2029],
        [0.7275, 0.9857, 0.0118, 0.3275, 0.0589, 0.5126, 0.5592, 0.6488, 0.7902,
         0.4774, 0.4880, 0.7314, 0.6530, 0.8635, 0.7472, 0.3331, 0.0993, 0.4636,
         0.2288, 0.9994, 0.5288, 0.3932, 0.0774, 0.8933],
        [0.5079, 0.7633, 0.1753, 0.4448, 0.2593, 0.3004, 0.8854, 0.2029, 0.7240,
         0.8772, 0.5877, 0.7767, 0.6423, 0.2119, 0.9497, 0.3881, 0.0031, 0.5632,
         0.2758, 0.0044, 0.2446, 0.1874, 0.8278, 0.6857],
        [0.9038, 0.0716, 0.8883, 0.7081, 0.3212, 0.8256, 0.4879, 0.6371, 0.7438,
         0.1369, 0.3399, 0.8237, 0.8692, 0.3985, 0.7850, 0.8406, 0.8894, 0.4735,
         0.8656, 0.4068, 0.7159, 0.1402, 0.2501, 0.3329],
        [0.3607, 0.0606, 0.2636, 0.0187, 0.8026, 0.2264, 0.4512, 0.0349, 0.3901,
         0.2393, 0.3439, 0.7951, 0.5566, 0.4257, 0.5662, 0.4564, 0.6383, 0.2197,
         0.0145, 0.2134, 0.9869, 0.8251, 0.0700, 0.0705],
        [0.3008, 0.1006, 0.6156, 0.4474, 0.2631, 0.7130, 0.5051, 0.8267, 0.4238,
         0.6535, 0.6982, 0.1762, 0.8963, 0.6848, 0.9918, 0.5252, 0.0097, 0.8595,
         0.9184, 0.6012, 0.2057, 0.0190, 0.7669, 0.8043],
        [0.2415, 0.6756, 0.5670, 0.3633, 0.9305, 0.1351, 0.9881, 0.8859, 0.6021,
         0.9049, 0.4576, 0.6921, 0.9828, 0.1330, 0.9648, 0.0944, 0.6838, 0.7029,
         0.2011, 0.1805, 0.6594, 0.9635, 0.9402, 0.0698],
        [0.1250, 0.2533, 0.8920, 0.6441, 0.8941, 0.9447, 0.0276, 0.9619, 0.7331,
         0.4102, 0.3067, 0.1519, 0.1545, 0.3365, 0.2861, 0.0113, 0.4404, 0.7962,
         0.1725, 0.6810, 0.3242, 0.8868, 0.2839, 0.9124]])

示例输入的形状为：

torch.Size([16, 24])

示例输出为：

tensor([[ 4.1522e-01, -3.2700e-01,  9.1172e-03, -6.1888e-02, -1.8494e-01,
         -2.9054e-01, -1.9343e-01,  5.6759e-01, -3.9938e-01, -1.2904e-01],
        [ 4.4440e-01, -1.5679e-01,  1.1616e-02,  2.9539e-02, -2.9386e-01,
         -2.8688e-01, -1.5933e-01,  7.0789e-01, -4.6069e-01, -8.4947e-02],
        [ 7.5442e-01,  1.8296e-01, -3.3333e-01,  7.3114e-04, -3.2968e-01,
         -6.7464e-01, -4.0478e-01,  2.4784e-01, -5.8322e-01,  9.2814e-02],
        [ 8.3028e-01,  1.6494e-01, -3.9289e-01, -2.4119e-02, -4.8418e-01,
         -2.3117e-01, -4.0815e-02,  6.2574e-01, -2.5519e-01, -5.3377e-02],
        [ 4.2770e-01, -2.4377e-03, -3.9112e-01, -1.3542e-01, -3.8081e-01,
         -3.8285e-01, -4.7448e-01,  5.8784e-01, -3.0406e-01, -1.3579e-02],
        [ 7.6887e-01,  7.9071e-02, -3.8369e-01,  1.0205e-01, -1.5357e-01,
         -3.0189e-01, -3.2993e-01,  3.7510e-01, -3.1675e-01, -1.0732e-01],
        [ 4.3479e-01, -1.2732e-01,  1.1979e-01,  1.2100e-01, -3.0203e-01,
         -4.4923e-02,  5.6754e-02,  6.3813e-01, -2.5149e-01,  1.7411e-02],
        [ 5.5578e-01,  2.8458e-02, -1.1646e-01, -1.8116e-02, -4.7574e-01,
         -1.9563e-01, -3.2112e-01,  7.5235e-01, -8.7674e-02,  3.6035e-01],
        [ 5.1310e-01,  1.4181e-01, -4.7291e-01, -4.0445e-02, -2.2049e-01,
         -2.5418e-01, -4.1853e-01,  7.0641e-01, -1.4084e-01,  7.5134e-02],
        [ 4.6734e-01, -6.2220e-02, -2.0911e-01,  1.8278e-01, -1.1369e-02,
         -2.1890e-01, -2.1712e-01,  6.8521e-01, -3.2055e-01,  1.7521e-01],
        [ 3.7750e-01, -1.6350e-01, -1.9854e-01,  2.3672e-01, -6.3100e-02,
         -2.1848e-01, -3.1139e-01,  8.8211e-01, -1.0384e-01,  5.2338e-03],
        [ 4.7957e-01, -2.2193e-01, -7.3253e-02, -2.7233e-01, -2.3791e-01,
         -2.8745e-01, -3.2755e-01,  7.7636e-01, -2.6881e-01,  1.0174e-01],
        [ 2.9993e-01, -7.1785e-02,  8.6001e-02, -2.6847e-01, -5.0801e-01,
         -1.0333e-01, -1.6095e-02,  7.1711e-01, -1.1421e-01,  1.7704e-01],
        [ 8.7247e-01,  2.4618e-01, -5.8469e-01,  1.5451e-01, -6.9370e-03,
         -3.7577e-01, -3.7028e-01,  5.0505e-01, -3.5785e-01, -7.1428e-02],
        [ 7.0154e-01, -2.2334e-01, -2.2977e-01,  1.4461e-01, -4.1193e-01,
         -3.5081e-01, -3.9965e-01,  9.3359e-01, -2.8495e-01, -2.1805e-01],
        [ 6.6928e-01,  2.3889e-01, -2.0160e-01,  1.0350e-01, -2.1756e-01,
         -4.7708e-01, -2.5686e-01,  2.7162e-01, -3.4521e-01, -1.8047e-01]],
       grad_fn=<AddmmBackward0>)

示例输出的形状为：

torch.Size([16, 10])

### 卷积操作

卷积也是PyTorch中常见的操作：将上一层的图像经过卷积（滤波）后得到这一层的图像。负责卷积操作的模块为`torch.nn.Conv1d`（一维卷积），`torch.nn.Conv2d`（二维卷积）和`torch.nn.Conv3d`（三维卷积）。每层接收比自己要卷积的维度多两维的张量（多出来的两个维度分别为批大小`B`和通道数`C`）。不同于全连接层的是，卷积第二维（通道维度）的大小变化由自己指定，后面维度的大小变化由所设定的卷积核、边界大小、步长等参数决定。

In [8]:
demo_model = nn.Conv2d(2, 8, kernel_size = 3, stride = 2, padding = 1)
# 卷积核为3x3，边界大小为1，步长为2，通道数由2变为64，因此图像大小会由[B, 2, H, W]变为[B, 8, H/2, W/2]

demo_input = torch.rand(8, 2, 32, 32) # 批大小为8，宽和高都为32，形状为[B = 8, 2, 32, 32]

print("示例输入的形状为：")
print(demo_input.shape)

demo_output = demo_model(demo_input) # 经过全连接层后，形状会为[B = 8, 8, 16, 16]

print("示例输出的形状为：")
print(demo_output.shape)

示例输入的形状为：

torch.Size([8, 2, 32, 32])

示例输出的形状为：

torch.Size([8, 8, 16, 16])

### 激活函数

激活函数用于过滤信息，常见的激活函数有ReLU、Sigmoid等。PyTorch中定义了多种多样的激活函数，可以直接使用：

In [9]:
demo_model = nn.ReLU()

demo_input = -1.0 + 2.0 * torch.rand(6)

print("示例输入为：")
print(demo_input)

demo_output = demo_model(demo_input)

print("示例输出为：")
print(demo_output)

示例输入为：

tensor([ 0.5945,  0.5006, -0.9155,  0.0270,  0.6134, -0.5189])

示例输出为：

tensor([0.5945, 0.5006, 0.0000, 0.0270, 0.6134, 0.0000])

In [10]:
demo_model = nn.Sigmoid()

demo_input = -1.0 + 2.0 * torch.rand(6)

print("示例输入为：")
print(demo_input)

demo_output = demo_model(demo_input)

print("示例输出为：")
print(demo_output)

示例输入为：

tensor([ 0.2715, -0.8667,  0.2811, -0.8315, -0.2325,  0.3133])

示例输出为：

tensor([0.5675, 0.2959, 0.5698, 0.3033, 0.4421, 0.5777])

### 组合拳

单靠定义一个一个的独立模块无法构建大的神经网络，因此，需要一个能够将所有神经网络的组成部分排列在一起的容器。在PyTorch中，用来扮演这一角色的是`nn.Sequential`。它接收多个参数，并将其排列为一张能按顺序执行下来的大型神经网络。

In [11]:
demo_model = nn.Sequential(
    nn.Flatten(), # 将图像展开成一个巨大的一维向量
    nn.Linear(28 * 28, 10),
    nn.ReLU()
)

demo_input = torch.rand(16, 28, 28) # 模拟MNIST数据集

print("示例输入的形状为：")
print(demo_input.shape)

demo_output = demo_model(demo_input)

print("示例输出为：")
print(demo_output)
print("示例输出的形状为：")
print(demo_output.shape)

示例输入的形状为：

torch.Size([16, 28, 28])

示例输出为：

tensor([[0.0000, 0.1682, 0.1079, 0.1997, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1429],
        [0.0000, 0.0000, 0.3685, 0.2738, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1544],
        [0.0000, 0.3589, 0.0521, 0.1380, 0.0000, 0.0000, 0.0000, 0.0733, 0.0954,
         0.1040],
        [0.0000, 0.5184, 0.2672, 0.1439, 0.0570, 0.0000, 0.0000, 0.3087, 0.0603,
         0.4467],
        [0.1210, 0.3195, 0.1306, 0.2347, 0.0911, 0.0000, 0.0000, 0.0000, 0.1110,
         0.1512],
        [0.0000, 0.0000, 0.1296, 0.5880, 0.1808, 0.0000, 0.0000, 0.2866, 0.0000,
         0.0606],
        [0.0676, 0.0292, 0.0000, 0.1181, 0.0000, 0.0000, 0.0000, 0.2434, 0.0000,
         0.1957],
        [0.0360, 0.1452, 0.1893, 0.3121, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0690],
        [0.0745, 0.3306, 0.2409, 0.3370, 0.0857, 0.0000, 0.0000, 0.0134, 0.0000,
         0.0000],
        [0.0000, 0.0896, 0.1689, 0.0797, 0.2007, 0.0000, 0.0000, 0.0326, 0.0000,
         0.0941],
        [0.0449, 0.5009, 0.0000, 0.2722, 0.0673, 0.0000, 0.0000, 0.0597, 0.2493,
         0.0024],
        [0.0000, 0.4146, 0.0439, 0.3560, 0.0233, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1454],
        [0.1722, 0.6191, 0.0000, 0.2174, 0.2309, 0.0000, 0.0000, 0.0000, 0.0000,
         0.3222],
        [0.0000, 0.1337, 0.1853, 0.4079, 0.0597, 0.0000, 0.0000, 0.0280, 0.0467,
         0.2812],
        [0.0000, 0.2690, 0.2261, 0.4885, 0.0408, 0.0000, 0.0000, 0.1152, 0.0410,
         0.0074],
        [0.3884, 0.0000, 0.0000, 0.3716, 0.0891, 0.0000, 0.0000, 0.1117, 0.0000,
         0.1082]], grad_fn=<ReluBackward0>)

示例输出的形状为：

torch.Size([16, 10])

## 2.3 模块的小技巧

### 可以在模块里声明模块

一个模块可以当做另一个模块的属性存在：

In [13]:
class Residual(nn.Module):
    def __init__(self, channel: int) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(channel, channel, kernel_size = 3, stride = 1, padding = 1)
        self.activaion1 = nn.ReLU()
        self.conv2 = nn.Conv2d(channel, channel, kernel_size = 3, stride = 1, padding = 1)
        self.activaion2 = nn.ReLU()
    

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y = self.conv1(x)
        y = self.activaion1(y)
        y = self.conv2(y)
        y = self.activaion2(y)
        y = x + y
        return y


demo_model = Residual(3)

print("模型为：")
print(demo_model)

demo_input = torch.rand(16, 3, 28, 28)

print("示例输入的形状为：")
print(demo_input.shape)

demo_output = demo_model(demo_input)

print("示例输出的形状为：")
print(demo_output.shape)

模型为：

Residual(
  (conv1): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (activaion1): ReLU()
  (conv2): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (activaion2): ReLU()
)

示例输入的形状为：

torch.Size([16, 3, 28, 28])

示例输出的形状为：

torch.Size([16, 3, 28, 28])

### 可以自定义模块的打印

通过重载`extra_repr`方法，可以将模型中的自定义参数打印在控制台中：

In [14]:
class LinearAdd(nn.Module):
    def __init__(self, a: float, b: float) -> None:
        super().__init__()
        self.a = a
        self.b = b
    

    def extra_repr(self) -> str:
        return "a=%.3f, b=%.3f" % (self.a, self.b)
    

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        return self.a * x + self.b * y

demo_model = LinearAdd(0.25, 0.75)
print(demo_model)

LinearAdd(a=0.250, b=0.750)

知道如何通过模块构造神经网络之后，我们就可以着手构造我们的神经网络了。然而，单单会构造还不够，为了使神经网络更好地满足我们的需求，我们还应该学会训练它。在下一部分，我们会讨论由PyTorch构建出的神经网络应该如何训练。